quarkus.package.type=uber-jar

quarkus.rest-client."org.acme.SocketClient".url=http://producer-app:8083/api
# quarkus.rest-client.socket-api.url=http://localhost:8083
quarkus.rest-client.http2=true

quarkus.log.level=INFO
